---
title: "Non-decreasing growth rates"
header-includes:
- \usepackage{titling}
- \pretitle{\begin{center}}
- \posttitle{\end{center}}
output: 
  pdf_document:
    toc: false
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE, error = TRUE,
  dev = "png", dpi = 144
)

library(data.table); library(qgam); library(mgcViz); library(ggplot2)
library(tidyverse); library(readxl); library(here); library(sf); 
library(quantregGrowth)

# Negate function
'%notin%' <- function(x,y)!('%in%'(x,y))

# Set GGplot auto theme
theme_set(theme(panel.grid.major = element_line(color='lightgray'),
                panel.grid.minor = element_blank(),
                panel.background = element_blank(),
                panel.border = element_rect(color='black', linewidth=1, fill=NA),
                legend.position = "bottom",
                axis.text.x=element_text(size=12),
                axis.text.y=element_text(size=12),
                axis.title.x=element_text(size=14),
                axis.title.y=element_text(size=14, angle=90, vjust=2),
                plot.title=element_text(size=14, hjust = 0, vjust = 1.2),
                plot.caption=element_text(hjust=0, face='italic', size=12),
                strip.text.x=element_text(size=12)))
```

```{r loaddata}
# Set the name of the workbook
fname <- paste0(here('Clean_Data/seine_compiled_clean.xlsx'))
# Get info about all excel sheet names in workbook
sheets <- readxl::excel_sheets(fname)
# Read in as list item, each item is a sheet
data.all <- invisible(lapply(sheets, 
                           function(x) readxl::read_excel(fname, sheet = x)))
names(data.all) <- sheets
# Coerce list items to dataframes
data.all <- lapply(data.all, as.data.frame)

rm(fname, sheets)
```

```{r fixnames}
#### Join similar species ####
data.all$bio$species_name[
  data.all$bio$species_name %in% c('grubby sculpin',
                                     'longhorn sculpin',
                                     'shorthorn sculpin',
                                     'slimy sculpin',
                                     'striped sculpin',
                                     'unID sculpin')
] <- 'sculpin spp'

data.all$bio$species_name[
  data.all$bio$species_name %in% c('atlantic herring',
                                     'herring')
] <- 'atlantic herring'

data.all$bio$species_name[
  data.all$bio$species_name %in% c('banded killifish',
                                     'killifish')
] <- 'killifish spp'

data.all$bio$species_name[
  data.all$bio$species_name %in% c('northern pipefish',
                                     'pipefish')
] <- 'northern pipefish'

data.all$bio$species_name[
  data.all$bio$species_name %in% c('white mullet',
                                     'mullet')
] <- 'white mullet'

data.all$bio$species_name[
  data.all$bio$species_name %in% c('emerald shiner',
                                     'golden shiner',
                                     'unID shiner')
] <- 'shiner spp'

data.all$bio$species_name[
  data.all$bio$species_name %in% c('rock gunnel',
                                     'unID gunnel')
] <- 'rock gunnel'

data.all$bio$species_name[
  data.all$bio$species_name %in% c('threespine stickleback',
                                     'fourspine stickleback',
                                     'ninespine stickleback',
                                     'unID stickelback')
] <- 'stickleback spp'


```

```{r summary}
lengths <- dplyr::select(data.all$bio,
                         species_name, length_mm, date)

# Remove one large mummichog
lengths <- lengths[lengths$length_mm != 385,]

lengths$wk <- lubridate::isoweek(lengths$date)
lengths$year <- lubridate::year(lengths$date)
lengths$length_mm <- as.numeric(lengths$length_mm)
lengths <- lengths[!is.na(lengths$length_mm),]

# lengths$id <- paste0(lengths$species_name,'qrst', lengths$length_mm, 'qrst',
#                      lengths$wk, 'qrst', lengths$year)
# lengths <- dplyr::select(lengths, id)
# lengths <- as.data.frame(table(lengths))
# colnames(lengths) <- c('id', 'Freq')
# 
# lengths <- lengths %>%
#   separate(id, into=c('species_name', 'length_mm', 'wk', 'year'),
#            sep='qrst')

lengths$species_name <- as.factor(lengths$species_name)
lengths$length_mm <- as.numeric(lengths$length_mm)
lengths$wk <- as.numeric(lengths$wk)
lengths$year <- as.numeric(lengths$year)

biolims <- lengths %>% 
  group_by(species_name) %>% 
  summarise(min.length = min(length_mm),
            max.length = max(length_mm))

#### Focus on top 10 ####
lengths <- lengths[lengths$species_name %in% 
                     c('alewife', 'atlantic silverside',
                       'atlantic herring', 'green crab', 
                       'winter flounder', 'mummichog', 
                       'tomcod', 'sandlance'),]
biolims <- biolims[biolims$species_name %in% lengths$species_name,]

lengths <- lengths[with(lengths, order(species_name, wk, length_mm)),]

#### Split by period ####
lengths.1 <- lengths[lengths$year %in% c(2014:2018),]
lengths.2 <- lengths[lengths$year %in% c(2019:2023),]
```

```{r plots}
# Set desired quantiles
quants <- c(0.25, 0.5, 0.75, 0.95)

for(i in 1:nrow(biolims)){
  
  ### Raw length-frequency over weeks ###
  temp <- lengths[lengths$species_name == biolims$species_name[i],]
  tempwks <- as.data.frame(table(temp$wk))
    
  nrecords <- as.data.table(temp)[, .N, by = 'wk'][order(wk)]
  times <- NULL
  
  for(j in 1:nrow(nrecords)){
    if(nrecords[j]$N == 1){
      times <- c(times, nrecords[j]$wk)
    }else{
      times <- c(times, rep(nrecords[j]$wk, 2 ^ 8))
    }
  }
  print(
    ggplot() +
        geom_jitter(data = temp, aes(x = wk, y = length_mm, col=year),
                    alpha=0.35, width=0.2, stroke=NA, cex=2) +
        scale_color_viridis_c(option = 'viridis', name='Year') +
        theme(legend.text = element_text(angle = 45, vjust = 0.4)) +
        geom_density(data = temp, aes(x = after_stat(scaled) * 0.9, 
                                      y = length_mm, group = wk),
                     n = 2 ^ 8,
                     position = position_nudge(x = times),
                     trim = T, adjust = 1.5) +
        xlab('Week of year') + ylab('Length (mm)') +
        ggtitle(str_to_title(paste0(biolims$species_name[i]),
                              ' raw length frequency'))
  )
  
  if(temp$species_name[1] %in% c('sandlance', 'sculpin spp')){
    next()
  }
  
  ### Quantile regression for growth ###
  temp <- lengths[lengths$species_name == biolims$species_name[i],]
  temp$yr_fac <- as.factor(temp$year)
  
  o <- gcrq(length_mm ~ ps(wk, monotone=1, center=TRUE) + ps(year),
            tau=quants, data=temp)
  print(
    plot(o, res=TRUE, col=-1, conf.level=0.95, shade=TRUE)
  )
  print(
    plot(o, legend=TRUE, overla=15, grid=list(x=15, y=10), col=2, lty=1,
         ylab='Length (mm)', xlab= 'Week')
  )
  
  
    
}
```
